---
- name: Deploy Maven Artifact
  hosts: all
  become: yes

  tasks:
    - name: Create application directory
      file:
        path: /opt/hellomaven
        state: directory

    - name: Copy JAR
      copy:
        src: target/Hellomaven2-1.0-SNAPSHOT.jar
        dest: /opt/hellomaven/Hellomaven2.jar

    - name: Run application
      shell: |
        pkill -f Hellomaven2.jar || true
        nohup java -jar /opt/hellomaven/Hellomaven2.jar > /tmp/app.log 2>&1 &
